### ISSUE TITLE
Rationale and References for assigning a suberror code

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-dnsop/draft-ietf-dnsop-structured-dns-error#1]
Add some text to clarify the reasoning for the listed suberrors. 

A proposal is to echo the following in the text:  say basically that we can accept registering suberrors:
  *  for which a clear definition is provided and
  *  which provide more characterization of an error vs a “parent” error (8914).
 
Most of the current proposed entries in the draft have their counterparts defined in existing RFCs (RFC4949, RFC5901). These citations should be added to the draft.

**Comment by tireddy2** [comment]
I would say a clear definition in a specification accepted by IETF.

**Comment by danwing** [comment]
`7.  New Sub-Error Codes Definition

   Subsequent documents defining new Sub-Error codes MUST be accepted by
   IETF, MUST also provide a clear definition of the error code (in
   their Reference text), and MUST also provide more characterization
   than the [RFC8914] parent error.

   This document defines new IANA-registered Sub-Error codes, below.

7.1.  Reserved

   *  Number: 0
` ...

Perhaps like that?

**Comment by boucadair** [comment]
Thanks, Dan. I commented directly in #3 . BTW, it seems that we are mixing "meaning vs name/label". The details of provided in the subsections 7.x does not match what we have in the table and also the description right before that table.
