### ISSUE TITLE
Should we remove the specific display error examples?

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-dnsop/draft-ietf-dnsop-structured-dns-error#13]
Currently, the text says:

> Browsers will display errors such as "The security certificate presented by this website was not issued by a trusted certificate authority" (Internet Explorer/Edge"), "The site's security certificate is not trusted" (Chrome), "This Connection is Untrusted" (Firefox), "Safari can't verify the identity of the website ..." (Safari on MacOS). Applications might display even more cryptic error messages.

I'd lean towards not including these specific examples in an RFC, since they are a single snapshot in time, and are liable to change. If we cite them, we should be more specific, but the point is also accurate to just explain that the certificate errors create a very poor user experience.

**Comment by boucadair** [comment]
Fair point, @tfpauly.
