### ISSUE TITLE
IETF review required

### ISSUE THREAD

**Issue by tireddy2** [ietf-wg-dnsop/draft-ietf-dnsop-structured-dns-error#15]
Ben suggested that he would like to see the registries tightly controlled for sub-error codes and JSON attributes in EXTRA-TEXT. IETF review prevents the designated expert from being pressured for odd states.

**Comment by boucadair** [comment]
OK for JSON name. see #18 

I'm afraid IETF review is too restrictive for the suberror codes. Let's have that discussion in the list before making changes.
