### ISSUE TITLE
Client requests including empty EDE isn't currently interoperable

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-dnsop/draft-ietf-dnsop-structured-dns-error#26]
When sending an empty EDE option in client requests, I hit errors with both 8.8.8.8 and Ad Guard public DoH servers.

I ran two other tests, and for both of these cases, all of the resolvers I tried did accept the request:
- Choose a new EDNS option code point (I just tested 50, randomly)
- Use EDE but set the length to 2 and the error to 0 (other error), rather than a length of 0

**Comment by danwing** [comment]
EDE length=2 with INFO-CODE=0 works nicely.

Also because non-EDE-aware DNS responders can be vulnerable to attacks described in Security Considerations, the Security Considerations section currently suggests clients use draft-ietf-add-resolver-info to check if server supports EDE.  This needs better clarification in the document that client has to check draft-ietf-add-resolver-info before including EDE OPT in its DNS query.  This check will further help interop by only sending EDE in requests to servers that indicated support via draft-ietf-add-resolver-info.  However, it creates draft-ietf-add-resolver-info as another hurdle to deployment of Structured DNS error.

**Comment by tfpauly** [comment]
Using length=2 and INFO-CODE=0 sounds fine to me.

For the dependency on draft-ietf-add-resolver-info, I don't think we need to impose that dependency. I'd much prefer to allow clients to look at that optionally, but still be able to include the hint and use the extra text if it parses correctly.

**Comment by danwing** [comment]
The justification for signaling draft-ietf-add-resolver-info is in Security Considerations where it currently says:

` An attacker might inject (or modify) the EDE EXTRA-TEXT field with an
   DNS proxy or DNS forwarder that is unaware of EDE.  Such a DNS proxy
   or DNS forwarder will forward that attacker-controlled EDE option.
   To prevent such an attack, clients supporting this document MUST
   discard the EDE option if their DNS server does not signal EDE
   support via RESINFO [I-D.ietf-add-resolver-info].  As recommended in
   [I-D.ietf-add-resolver-info], RESINFO should be retrieved over an
   encrypted DNS channel or integrity protected with DNSSEC.`

should we soften that?  The authors have argued back and forth on the risk of this attack versus deployment, code, and operational complexity of draft-ietf-add-resolver-info signaling.

**Comment by fl1ger** [comment]
Moin!

We already require an encrypted channel, so the chances of an attacker injecting something are minimal unless you connect to an attacker in which case all bets are off anyway. I don't think this RESINFO requirement is needed and would delete it all together, but at least change the MUST to a MAY or if you feel strong about it a SHOULD.

So long
-Ralf

**Comment by boucadair** [comment]
I also don't think we need to have RESINFO as normative here. We can tweak the text, e.g.,

s/MUST...RESINFO [I-D.ietf-add-resolver-info]/SHOULD ... a mechanism such as RESINFO [I-D.ietf-add-resolver-info]

This will be consistent with the other uses in https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-structured-dns-error/pull/27/. 

There are other ways to avoid "trusting" random resolvers.

**Comment by boucadair** [comment]
> but at least change the MUST to a MAY

This will still require listing RESINFO as normative as per "[IESG statement](https://www.ietf.org/about/groups/iesg/statements/normative-informative-references/)"

> Note 1: Even references that are relevant only for optional features must be classified as normative if they meet the above conditions for normative references. 

We need more text tweaking.

**Comment by danwing** [comment]
EDE length=2 with INFO-CODE=0 is now in -03.  RESINFO (I-D.ietf-add-resolver-info) is now significantly reduced in its importance and need in -03.
