### ISSUE TITLE
redundant item

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-dnsop/draft-ietf-dnsop-structured-dns-error#55]
https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-structured-dns-error/blob/8dffcaf2031284ec3c40b114e8d2145ff57fc620/draft-ietf-dnsop-structured-dns-error.md?plain=1#L407C1-L407C39

Isn't this redundant with "The DNS client MUST ignore any other JSON names that it does not support." or the intent here is to cover the forwarder case? 

Also, remember that the actions are "ordered":

>    On receipt of a DNS response with an EDE option from a DNS responder,
>    the following ordered actions are performed on the EXTRA-TEXT field:

**Comment by danwing** [comment]
Removed PR #56
